version: '3'
services:
  nginx: 
    image: nginx:latest
    container_name: k8s-dashbaord-nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    network_mode: 'bridge'
    ports:
      - 8080:8080
    restart: always